import gather_to_same_format
gather_to_same_format.gather_to_same_format('training_pipeline/training_set/train_750_Prompts_1_revised.json', 'training_pipeline/training_set/train_750_Responses_1_revised.json')
gather_to_same_format.gather_to_same_format('training_pipeline/training_set/train_200_Prompts_2_revised.json', 'training_pipeline/training_set/train_200_Responses_2_revised.json')
gather_to_same_format.gather_to_same_format('training_pipeline/training_set/train_50_Prompts_3_revised.json', 'training_pipeline/training_set/train_50_Responses_3_revised.json') 